### ISSUE TITLE
I'm so sorry for writing here, I think I'm making similiar project.

### ISSUE THREAD

**Issue by Vasukaman** [eg9y/promptsandbox.io#8]
I think I'm making similiar project
https://github.com/Vasukaman/AiParty
(Your is way more complete and has way better UI ofcource)

I would love to chat if possible. Just generally about our projects and what type of workflows we can make with it.

You can message me on:
Twitter: https://twitter.com/ShittyVasuka
Reddit: https://www.reddit.com/user/VasukaTupoi
Telegram: https://t.me/Vasukaman
Discord: Vasuka#5310

Once again, I'm sorry for writing here, but I couldn't find another way

**Comment by eg9y** [comment]
> Once again, I'm sorry for writing here, but I couldn't find another way

Oh right 😅, I should probably add a Contact section in the readme. 

Sure, let's chat!

**Comment by eg9y** [comment]
6dc97a7
